# Generated by Django 5.0.2 on 2024-02-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address_country', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_zip', models.CharField(max_length=10)),
                ('address_street', models.CharField(max_length=100)),
                ('address_aptnum', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('social_instagram', models.URLField()),
                ('social_twitter', models.URLField()),
                ('social_github', models.URLField()),
                ('social_linkedin', models.URLField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
