# Generated by Django 5.0.2 on 2024-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
