# Generated by Django 5.0.2 on 2024-02-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
